name: Avci 2 V2 Multi-Chain

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore Avci DB
        uses: actions/cache/restore@v4
        with:
          path: avci2.db
          key: avci2-db-${{ github.run_id }}
          restore-keys: |
            avci2-db-        

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Run Avci 2 V2
        env:
         JUPITER_API_KEY: ${{ secrets.JUPITER_API_KEY }}
        run: python scanner.py
      - name: Save Avci DB
        if: always()
        uses: actions/cache/save@v4
        with:
          path: avci2.db
          key: avci2-db-${{ github.run_id }}
